# add this line for pid directive to overcome permission problems
pid /var/home/adrian/linux-sync-lab/nginx.pid;

#1. Events block (Required even if empty)
events {
	worker_connections 1024;
}

#2. Main http block
http {
	# redirect logs
	access_log /var/home/adrian/linux-sync-lab/access.log;
	error_log /var/home/adrian/linux-sync-lab/error.log;
	
	# redirect temporary paths
	client_body_temp_path /var/home/adrian/linux-sync-lab/client_body;
	proxy_temp_path /var/home/adrian/linux-sync-lab/proxy_temp;
	fastcgi_temp_path /var/home/adrian/linux-sync-lab/fastcgi_temp;
	uwsgi_temp_path /var/home/adrian/linux-sync-lab/uwsgi_temp;
	scgi_temp_path /var/home/adrian/linux-sync-lab/scgi_temp;

	types_hash_max_size 4096;
	types_hash_bucket_size 64;

	#inclusion of mime types helps the browser understand CSS/Images
	include /etc/nginx/mime.types;

	server {
		# Port 8080 is safe for testing inside a container
		listen 8080;
		server_name localhost;

		# where your index.html file is physically located
		location / 
			{root /var/home/adrian/linux-sync-lab;
				index index.html;
			}
			# Example of a custom error page later
			error_page 500 502 503 504 /50x.html;
		}
}
